
version: '3.1'

services:
  app-config:
    image: config-demo
    restart: always
    ports:
      - 9101:9101

  app-client:
    image: client-demo
    restart: always
    ports:
      - 8080:8080

  app-eureka:
    image: paymybuddy-demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - "app-config"

  app-gateway:
    image: gateway-demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - "app-config"
      - "app-eureka"

  app-produits:
    image: produits-demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - "app-config"
      - "app-eureka"



