
version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb



  app-config:
    image: config_container_learn_microservices
    restart: always
    ports:
      - 9101:9101

  app-client:
    image: client_container_learn_microservices
    restart: always
    ports:
      - 8080:8080

  app-eureka:
    image: eureka_container_learn_microservices
    restart: always
    ports:
      - 9102:9102
    depends_on:
      - "app-config"

  app-gateway:
    image: gateway_container_learn_microservices
    restart: always
    ports:
      - 9004:9004
    depends_on:
      - "app-config"
      - "app-eureka"

  app-produits:
    image: produits_container_learn_microservices
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - "app-config"
      - "app-eureka"

volumes:
  data: {}

