
version: '3.1'

services:
  app-config:
    image: config_container_learn_microservices
    restart: always
    ports:
      - 9101:9101

  app-client:
    image: client_container_learn_microservices
    restart: always
    ports:
      - 8080:8080

  app-eureka:
    image: eureka_container_learn_microservices
    restart: always
    ports:
      - 9102:9102
    depends_on:
      - "app-config"

  app-gateway:
    image: gateway_container_learn_microservices
    restart: always
    ports:
      - 9004:9004
    depends_on:
      - "app-config"
      - "app-eureka"

  app-produits:
    image: produits_container_learn_microservices
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - "app-config"
      - "app-eureka"



